#!/usr/bin/env python3
"""Generate or verify SHR Sampler's project-authored public factory package."""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import math
import struct
import sys
import wave
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "instruments" / "shr-clear-tone.shrinst"
SAMPLE = PACKAGE / "samples" / "clear-tone.wav"
MANIFEST = PACKAGE / "manifest.json"
SAMPLE_RATE = 44_100
CYCLE_FRAMES = 168
FRAME_COUNT = CYCLE_FRAMES * 128


def wav_bytes() -> bytes:
    cycle = []
    for frame in range(CYCLE_FRAMES):
        phase = 2.0 * math.pi * frame / CYCLE_FRAMES
        value = 0.42 * math.sin(phase) + 0.08 * math.sin(3.0 * phase)
        cycle.append(max(-32_768, min(32_767, round(value * 32_767.0))))
    raw = b"".join(
        struct.pack("<h", cycle[frame % CYCLE_FRAMES])
        for frame in range(FRAME_COUNT)
    )
    output = io.BytesIO()
    with wave.open(output, "wb") as wav:
        wav.setnchannels(1)
        wav.setsampwidth(2)
        wav.setframerate(SAMPLE_RATE)
        wav.writeframes(raw)
    return output.getvalue()


def manifest_bytes(sample: bytes) -> bytes:
    document = {
        "format_version": 1,
        "instrument_id": "shr-clear-tone",
        "display_name": "SHR Clear Tone",
        "metadata": {
            "author": "SHR Sampler project",
            "source": "Deterministic project-authored mathematical waveform",
            "licence": "CC0-1.0",
            "attribution": "None required",
            "notes": (
                "Public neutral factory start generated by "
                "scripts/generate_factory_instruments.py"
            ),
        },
        "max_polyphony": 12,
        "zones": [
            {
                "id": "clear-tone-zone",
                "sample": {
                    "path": "samples/clear-tone.wav",
                    "sha256": hashlib.sha256(sample).hexdigest(),
                    "metadata": {
                        "sample_rate": SAMPLE_RATE,
                        "channels": 1,
                        "frames": FRAME_COUNT,
                    },
                },
                "key_low": 0,
                "key_high": 127,
                "velocity_low": 1,
                "velocity_high": 127,
                "root_note": 60,
                "coarse_transpose": 0,
                "fine_tune_cents": 0.0,
                "gain_db": -6.0,
                "pan": 0.0,
                "playback_mode": "gated",
                "loop_mode": {
                    "mode": "forward",
                    "start_frame": CYCLE_FRAMES,
                    "end_frame": CYCLE_FRAMES * 2,
                },
                "envelope": {
                    "attack_seconds": 0.005,
                    "decay_seconds": 0.08,
                    "sustain_level": 0.75,
                    "release_seconds": 0.25,
                },
                "sample_start_frame": 0,
                "sample_end_frame": FRAME_COUNT,
            }
        ],
    }
    return (json.dumps(document, indent=2, ensure_ascii=False) + "\n").encode()


def expected_files() -> dict[Path, bytes]:
    sample = wav_bytes()
    return {SAMPLE: sample, MANIFEST: manifest_bytes(sample)}


def check() -> int:
    expected = expected_files()
    for path, content in expected.items():
        if not path.is_file() or path.is_symlink() or path.read_bytes() != content:
            print(f"factory instrument drift: {path.relative_to(ROOT)}", file=sys.stderr)
            return 1
    actual = {path for path in PACKAGE.rglob("*") if path.is_file()}
    if actual != set(expected):
        print("factory instrument contains missing or extra files", file=sys.stderr)
        return 1
    print("factory instrument matches its deterministic generator")
    return 0


def write() -> int:
    expected = expected_files()
    SAMPLE.parent.mkdir(parents=True, exist_ok=True)
    for path, content in expected.items():
        temporary = path.with_name(path.name + ".tmp")
        temporary.write_bytes(content)
        temporary.replace(path)
    return check()


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()
    return write() if args.write else check()


if __name__ == "__main__":
    raise SystemExit(main())
